LEAFLET_VERSION=1.9.4
# PROTOMAPS_LEAFLET_VERSION=4.0.1

leaflet:
	curl -s -o www/css/leaflet.css https://unpkg.com/leaflet@$(LEAFLET_VERSION)/dist/leaflet.css
	curl -s -o www/javascript/leaflet.js https://unpkg.com/leaflet@$(LEAFLET_VERSION)/dist/leaflet.js

# protomaps:
# 	curl -s -o www/javascript/protomaps-leaflet.js https://unpkg.com/protomaps-leaflet@$(PROTOMAPS_LEAFLET_VERSION)/dist/protomaps-leaflet.js
